FROM node:24 as development

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV=development

EXPOSE 3002

CMD ["npm", "run", "dev"]

FROM node:24 AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

ENV NODE_ENV=production

EXPOSE 3002

CMD ["npm", "start"]