FROM node:24 AS development

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3001

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]

FROM node:24 AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

EXPOSE 3001

ENV NODE_ENV=production

CMD ["npm", "run", "start"]