services:
    cliente-api:
        build:
            context: ./cliente-api
            dockerfile: dockerfile
            target: production
        ports:
            - ${CLIENTE_PORT}:3001
        env_file:
            - ./cliente-api/.env
        restart: unless-stopped
    producto-api:
        build:
            context: ./producto-api
            dockerfile: dockerfile
            target: production
        ports:
            - ${PRODUCTO_PORT}:3002
        env_file:
            - ./producto-api/.env
        restart: unless-stopped
    compra-api:
        build:
            context: ./compra-api
            dockerfile: dockerfile
            target: production
        ports:
            - ${COMPRA_PORT}:3003
        env_file:
            - ./compra-api/.env
        restart: unless-stopped