FROM node:24 as development

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV CLIENTE_API_URL=http://localhost:3001

ENV PRODUCTO_API_URL=http://localhost:3002

EXPOSE 3003

CMD ["npm", "run", "dev"]

FROM node:24 AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

ENV NODE_ENV=production

EXPOSE 3003

CMD ["npm", "start"]